# Generated by Rishabh on 2023-10-02 00:55
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def create_author_group(*args, **kwargs):
    Group.objects.create(name="Author")
    print("Group: Author, created successfully!!!")


def remove_author_group(*args, **kwargs):
    try:
        Group.objects.get(name="Author").delete()
        print("Group: Author, deleted successfully!!!")
    except ObjectDoesNotExist:
        print("Group: Author, doesn't exist")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog_app", "0001_initial")
    ]

    operations = [
        migrations.RunPython(create_author_group, remove_author_group)
    ]
